name: tmdb_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# flutter_icons:
#   image_path: "assets/icons/icon_app.png"
#   ios: true
#   android: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
